using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickFrame.Security.ActiveDirectory.Api
{
    public enum ADS_SEARCHPREF {
		ADS_SEARCHPREF_ASYNCHRONOUS = 0,
		ADS_SEARCHPREF_DEREF_ALIASES = 1,
		ADS_SEARCHPREF_SIZE_LIMIT = 2,
		ADS_SEARCHPREF_TIME_LIMIT = 3,
		ADS_SEARCHPREF_ATTRIBTYPES_ONLY = 4,
		ADS_SEARCHPREF_SEARCH_SCOPE = 5,
		ADS_SEARCHPREF_TIMEOUT = 6,
		ADS_SEARCHPREF_PAGESIZE = 7,
		ADS_SEARCHPREF_PAGED_TIME_LIMIT = 8,
		ADS_SEARCHPREF_CHASE_REFERRALS = 9,
		ADS_SEARCHPREF_SORT_ON = 10,
		ADS_SEARCHPREF_CACHE_RESULTS = 11,
		ADS_SEARCHPREF_DIRSYNC = 12,
		ADS_SEARCHPREF_TOMBSTONE = 13,
		ADS_SEARCHPREF_VLV = 14,
		ADS_SEARCHPREF_ATTRIBUTE_QUERY = 15,
		ADS_SEARCHPREF_SECURITY_MASK = 16,
		ADS_SEARCHPREF_DIRSYNC_FLAG = 17,
		ADS_SEARCHPREF_EXTENDED_DN = 18
	}
}
