using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuickFrame.ActiveDirectory.Api
{
	public enum ADSTYPE {
		ADSTYPE_INVALID = 0,
		ADSTYPE_DN_STRING = (ADSTYPE_INVALID + 1), //1
		ADSTYPE_CASE_EXACT_STRING = (ADSTYPE_DN_STRING + 1), //2
		ADSTYPE_CASE_IGNORE_STRING = (ADSTYPE_CASE_EXACT_STRING + 1), //3
		ADSTYPE_PRINTABLE_STRING = (ADSTYPE_CASE_IGNORE_STRING + 1), //4
		ADSTYPE_NUMERIC_STRING = (ADSTYPE_PRINTABLE_STRING + 1), //5
		ADSTYPE_BOOLEAN = (ADSTYPE_NUMERIC_STRING + 1), //6
		ADSTYPE_INTEGER = (ADSTYPE_BOOLEAN + 1), //7
		ADSTYPE_OCTET_STRING = (ADSTYPE_INTEGER + 1), //8
		ADSTYPE_UTC_TIME = (ADSTYPE_OCTET_STRING + 1), //9
		ADSTYPE_LARGE_INTEGER = (ADSTYPE_UTC_TIME + 1), //10
		ADSTYPE_PROV_SPECIFIC = (ADSTYPE_LARGE_INTEGER + 1), //11
		ADSTYPE_OBJECT_CLASS = (ADSTYPE_PROV_SPECIFIC + 1), //12
		ADSTYPE_CASEIGNORE_LIST = (ADSTYPE_OBJECT_CLASS + 1), //13
		ADSTYPE_OCTET_LIST = (ADSTYPE_CASEIGNORE_LIST + 1), //14
		ADSTYPE_PATH = (ADSTYPE_OCTET_LIST + 1), //15
		ADSTYPE_POSTALADDRESS = (ADSTYPE_PATH + 1), //16
		ADSTYPE_TIMESTAMP = (ADSTYPE_POSTALADDRESS + 1), //17
		ADSTYPE_BACKLINK = (ADSTYPE_TIMESTAMP + 1), //18
		ADSTYPE_TYPEDNAME = (ADSTYPE_BACKLINK + 1), //19
		ADSTYPE_HOLD = (ADSTYPE_TYPEDNAME + 1), //20
		ADSTYPE_NETADDRESS = (ADSTYPE_HOLD + 1), //21
		ADSTYPE_REPLICAPOINTER = (ADSTYPE_NETADDRESS + 1), //22
		ADSTYPE_FAXNUMBER = (ADSTYPE_REPLICAPOINTER + 1), //23
		ADSTYPE_EMAIL = (ADSTYPE_FAXNUMBER + 1), //24
		ADSTYPE_NT_SECURITY_DESCRIPTOR = (ADSTYPE_EMAIL + 1), //25
		ADSTYPE_UNKNOWN = (ADSTYPE_NT_SECURITY_DESCRIPTOR + 1), //26
		ADSTYPE_DN_WITH_BINARY = (ADSTYPE_UNKNOWN + 1), //27
		ADSTYPE_DN_WITH_STRING = (ADSTYPE_DN_WITH_BINARY + 1) //28
	}
}
